const data = {
  users: [
    {
      email: "user@example.com",
      password: bcrypt.hashSync("Uu12345"),
      isAdmin: false,
    },
    {
      email: "seller@example.com",
      password: bcrypt.hashSync("Aa12345"),
      isAdmin: true,
    },
    {
      email: "admin@example.com",
      password: bcrypt.hashSync("Aa12345"),
      isAdmin: true,
      storeId: 11
    },
    {
      email: "tamlyn@super.admin",
      password: bcrypt.hashSync("Tt12345"),
      isAdmin: true,
    }
  ],
  products: [
    {
      name: "Star movie",
      slug: 'movie1',
      category: "Movies",
      image: "http://dummyimage.com/450x600.png/fca36f/ffffff",
      price: 3.56,
      countInStock: 33,
      brand: "Star Bulk Carriers Corp.",
      storeId: 7,
      rating: 4.5,
      numReviews: 10,
      description: "Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante."
    },
    {
      name: "Beauty shoe",
      slug: 'shoe1',
      category: "Shoes",
      image: "http://dummyimage.com/450x600.png/5a8b5a/ffffff",
      price: 3.90,
      countInStock: 48,
      brand: "Sally Beauty Holdings, Inc.",
      storeId: 1,
      rating: 4,
      numReviews: 10,
      description: "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy."
    },
    {
      name: "Anthera grocery",
      slug: 'grocery1',
      category: "Grocery",
      image: "http://dummyimage.com/450x600.png/5fa2dd/ffffff",
      price: 5.75,
      countInStock: 28,
      brand: "Anthera Pharmaceuticals, Inc.",
      storeId: 5,
      rating: 5,
      numReviews: 10,
      description: "Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. "
    },
    {
      name: "Motorola toy",
      slug: 'toy1',
      category: "Toys",
      image: "http://dummyimage.com/450x600.png/b17dae/ffffff",
      price: 1.01,
      countInStock: 48,
      brand: "Motorola Solutions, Inc.",
      storeId: 3,
      rating: 3.5,
      numReviews: 10,
      description: "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros."
    },
    {
      name: "Veritex movie",
      slug: 'movie2',
      category: "Movies",
      image: "http://dummyimage.com/450x600.png/fca36f/ffffff",
      price: 0.92,
      countInStock: 26,
      brand: "Veritex Holdings, Inc.",
      storeId: 2,
      rating: 4,
      numReviews: 10,
      description: " Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero."
    },
  ]
}

export default data;
/*
hansenands@store.com 
Hansen and Sons
lorem10

Littel, Walter and Bartoletti
lwandb@store.com

Kassulke-Cole
kc@store.com

steuber@store.com
Steuber LLC

ckands@store.com
Collier, Kassulke and Schinner

smith@store.com
Smith Group


 Aliquid labore impedit quod.
, doloribus laborum quaerat fugit!  nesciunt et consectetur dolorem odit hic fugit ad aspernatur maxime sed harum tenetur unde eligendi? Sit qui quidem ipsam quae delectus fuga, sunt autem quod nostrum minima perferendis porro officiis aliquam culpa. Dignissimos, assumenda autem. Rem adipisci earum, excepturi delectus distinctio blanditiis laudantium? Quas, aperiam! Nam laborum magnam ullam eligendi, minus accusantium in voluptate? Porro ex sed veritatis ut esse minima ipsam illo possimus?

{"id":6,"title":"PowerShares S&P SmallCap Energy Portfolio","description":"Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.","imageUrl":"http://dummyimage.com/172x100.png/cc0000/ffffff",
  "storeId":2,"price":"$9.57","quantity":33,"category":"Sports"},

{"id":7,"title":"Leading Brands Inc","description":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.","imageUrl":"http://dummyimage.com/184x100.png/cc0000/ffffff",
  "storeId":10,"price":"$2.81","quantity":48,"category":"Beauty"},
{"id":8,"title":"BiondVax Pharmaceuticals Ltd.","description":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","imageUrl":"http://dummyimage.com/150x100.png/cc0000/ffffff",
  "storeId":5,"price":"$0.39","quantity":49,"category":"Baby"},

{"id":9,"title":"MKS Instruments, Inc.","description":"Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","imageUrl":"http://dummyimage.com/155x100.png/ff4444/ffffff",
  "storeId":6,"price":"$4.32","quantity":5,"category":"Clothing"},

{"id":10,"title":"MediWound Ltd.","description":"Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.","imageUrl":"http://dummyimage.com/246x100.png/dddddd/000000",
  "storeId":6,"price":"$8.57","quantity":48,"category":"Garden"},
{"id":11,"title":"Just Energy Group, Inc.","description":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.","imageUrl":"http://dummyimage.com/206x100.png/ff4444/ffffff",
  "storeId":4,"price":"$4.55","quantity":46,"category":"Games"},

{"id":12,"title":"Maxim Integrated Products, Inc.","description":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.","imageUrl":"http://dummyimage.com/178x100.png/ff4444/ffffff",
  "storeId":8,"price":"$4.45","quantity":49,"category":"Industrial"},
{"id":13,"title":"ZAGG Inc","description":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.","imageUrl":"http://dummyimage.com/166x100.png/5fa2dd/ffffff",
  "storeId":1,"price":"$5.52","quantity":12,"category":"Grocery"},

{"id":14,"title":"Champions Oncology, Inc.","description":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.","imageUrl":"http://dummyimage.com/136x100.png/dddddd/000000",
  "storeId":7,"price":"$0.30","quantity":13,"category":"Outdoors"},

{"id":15,"title":"EDAP TMS S.A.","description":"Cras pellentesque volutpat dui.","imageUrl":"http://dummyimage.com/187x100.png/ff4444/ffffff",
  "storeId":10,"price":"$9.48","quantity":43,"category":"Beauty"},

{"id":16,"title":"Lennar Corporation","description":"Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.","imageUrl":"http://dummyimage.com/124x100.png/5fa2dd/ffffff",
  "storeId":3,"price":"$8.75","quantity":12,"category":"Books"},

{"id":17,"title":"Denbury Resources Inc.","description":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.","imageUrl":"http://dummyimage.com/178x100.png/ff4444/ffffff",
  "storeId":2,"price":"$5.09","quantity":50,"category":"Computers"},

{"id":18,"title":"American Eagle Outfitters, Inc.","description":"Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.","imageUrl":"http://dummyimage.com/235x100.png/dddddd/000000",
  "storeId":8,"price":"$1.36","quantity":20,"category":"Kids"},

{"id":19,"title":"Dun & Bradstreet Corporation (The)","description":"Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.","imageUrl":"http://dummyimage.com/117x100.png/5fa2dd/ffffff",
  "storeId":7,"price":"$9.35","quantity":7,"category":"Books"},

{"id":24,"title":"Aspen Insurance Holdings Limited","description":"Integer ac neque.","imageUrl":"http://dummyimage.com/188x100.png/5fa2dd/ffffff",
  "storeId":6,"price":"$3.34","quantity":5,"category":"Sports"},
{"id":25,"title":"Fortress Investment Group LLC","description":"In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","imageUrl":"http://dummyimage.com/184x100.png/ff4444/ffffff",
  "storeId":6,"price":"$6.78","quantity":11,"category":"Automotive"},
{"id":26,"title":"Amyris, Inc.","description":"Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.","imageUrl":"http://dummyimage.com/205x100.png/5fa2dd/ffffff",
  "storeId":5,"price":"$6.17","quantity":14,"category":"Movies"},

{"id":27,"title":"LMP Capital and Income Fund Inc.","description":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.","imageUrl":"http://dummyimage.com/242x100.png/cc0000/ffffff",
  "storeId":6,"price":"$5.40","quantity":23,"category":"Baby"},

{"id":28,"title":"Calamos Global Dynamic Income Fund","description":"Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","imageUrl":"http://dummyimage.com/221x100.png/cc0000/ffffff",
  "storeId":1,"price":"$6.27","quantity":2,"category":"Clothing"},
{"id":29,"title":"Calgon Carbon Corporation","description":"Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.","imageUrl":"http://dummyimage.com/120x100.png/cc0000/ffffff",
  "storeId":4,"price":"$2.31","quantity":47,"category":"Shoes"},
{"id":30,"title":"Olympic Steel, Inc.","description":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.","imageUrl":"http://dummyimage.com/129x100.png/cc0000/ffffff",
  "storeId":1,"price":"$1.71","quantity":12,"category":"Sports"},
{"id":31,"title":"Atlantic Capital Bancshares, Inc.","description":"In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","imageUrl":"http://dummyimage.com/124x100.png/dddddd/000000",
  "storeId":6,"price":"$4.04","quantity":41,"category":"Shoes"},
{"id":32,"title":"Washington Prime Group Inc.","description":"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","imageUrl":"http://dummyimage.com/101x100.png/ff4444/ffffff",
  "storeId":10,"price":"$9.79","quantity":49,"category":"Beauty"},
{"id":33,"title":"Lennar Corporation","description":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","imageUrl":"http://dummyimage.com/128x100.png/cc0000/ffffff",
  "storeId":8,"price":"$6.68","quantity":26,"category":"Health"},
{"id":34,"title":"Antero Resources Corporation","description":"Proin at turpis a pede posuere nonummy.","imageUrl":"http://dummyimage.com/246x100.png/5fa2dd/ffffff",
  "storeId":10,"price":"$6.83","quantity":48,"category":"Kids"},
{"id":35,"title":"Federal Agricultural Mortgage Corporation","description":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","imageUrl":"http://dummyimage.com/249x100.png/cc0000/ffffff",
  "storeId":3,"price":"$8.27","quantity":4,"category":"Toys"},
{"id":36,"title":"Check-Cap Ltd.","description":"Maecenas pulvinar lobortis est. Phasellus sit amet erat.","imageUrl":"http://dummyimage.com/232x100.png/cc0000/ffffff",
  "storeId":4,"price":"$4.41","quantity":1,"category":"Clothing"},
{"id":37,"title":"Fresenius Medical Care Corporation","description":"Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.","imageUrl":"http://dummyimage.com/198x100.png/ff4444/ffffff",
  "storeId":5,"price":"$7.98","quantity":43,"category":"Kids"},
{"id":38,"title":"Ardelyx, Inc.","description":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.","imageUrl":"http://dummyimage.com/179x100.png/5fa2dd/ffffff",
  "storeId":9,"price":"$1.90","quantity":49,"category":"Books"},
{"id":39,"title":"Papa Murphy's Holdings, Inc.","description":"Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.","imageUrl":"http://dummyimage.com/144x100.png/ff4444/ffffff",
  "storeId":9,"price":"$4.70","quantity":35,"category":"Health"},
{"id":40,"title":"First Trust Mid Cap Value AlphaDEX Fund","description":"Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.","imageUrl":"http://dummyimage.com/207x100.png/5fa2dd/ffffff",
  "storeId":10,"price":"$5.35","quantity":26,"category":"Sports"},
{"id":41,"title":"Chesapeake Energy Corporation","description":"Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","imageUrl":"http://dummyimage.com/131x100.png/ff4444/ffffff",
  "storeId":10,"price":"$4.96","quantity":45,"category":"Outdoors"},

[
{"id":7,"email":"hansenandsons@store.com","password":"xxnBq4wz","role":"admin",
  "uniqueStoreId":2},
  {"id":10,"email":"mzanuciolii9@sbwire.com","password":"f4yDwc","role":"admin",
    "uniqueStoreId":1},
    {"id":12,"email":"fwiddopb@rambler.ru","password":"fJ6w4emm","role":"admin",
      "uniqueStoreId":10},
      {"id":13,"email":"agommesc@hp.com","password":"ok4Qx45","role":"admin",
        "uniqueStoreId":6},
        {"id":18,"email":"atemprellh@discuz.net","password":"YYLBGf","role":"admin",
          "uniqueStoreId":1},


{"id":1,"email":"wbampfield0@vinaora.com","password":"IXoPdcjvPF4Y","role":"user",
  "uniqueStoreId":4},
{"id":2,"email":"eargyle1@discovery.com","password":"zSwyT8GV1","role":"user",
  "uniqueStoreId":7},
{"id":3,"email":"bcroisier2@tinyurl.com","password":"MmRfw9Xqu","role":"user",
  "uniqueStoreId":6},
{"id":4,"email":"qvasichev3@elegantthemes.com","password":"BWV8qNBX","role":"user",
  "uniqueStoreId":9},
{"id":5,"email":"zabad4@github.io","password":"rN4et5","role":"user",
  "uniqueStoreId":4},
{"id":6,"email":"cmcgahy5@archive.org","password":"7msf26U41g","role":"user",
  "uniqueStoreId":7},
{"id":8,"email":"tpristnor7@51.la","password":"bGv9dJV","role":"user",
  "uniqueStoreId":5},
{"id":9,"email":"plente8@disqus.com","password":"gs5faw","role":"user",
  "uniqueStoreId":7},
{"id":11,"email":"rservanta@ovh.net","password":"ZtPT4ve9KKnX","role":"user",
  "uniqueStoreId":2},
{"id":14,"email":"tclarycottd@redcross.org","password":"5rMu2pflm7","role":"user",
  "uniqueStoreId":10},
{"id":15,"email":"fmcmorlande@bigcartel.com","password":"KkyWzHZpeX","role":"user",
  "uniqueStoreId":9},
{"id":16,"email":"owaudbyf@myspace.com","password":"VnOIoyqT","role":"user",
  "uniqueStoreId":9},
{"id":17,"email":"dkarpfg@discovery.com","password":"InqXQx5","role":"user",
  "uniqueStoreId":4},
{"id":19,"email":"hdominiquei@ft.com","password":"lVGdOfga","role":"super-admin",
  "uniqueStoreId":5},
{"id":20,"email":"dgeerj@jigsy.com","password":"KLwp84TFQIY","role":"user",
  "uniqueStoreId":9},
{"id":21,"email":"layrsk@odnoklassniki.ru","password":"LgdFvCYoU","role":"super-admin",
  "uniqueStoreId":6},
{"id":22,"email":"mbraunsteinl@amazon.co.uk","password":"V3HAd2ASh","role":"user",
  "uniqueStoreId":7},
{"id":23,"email":"tdictem@mapy.cz","password":"goND1pToI","role":"user",
  "uniqueStoreId":7},
{"id":24,"email":"mavisonn@senate.gov","password":"USZoqlrTU","role":"user",
  "uniqueStoreId":6},
{"id":25,"email":"mhicko@reddit.com","password":"wtpjLP","role":"user",
  "uniqueStoreId":10},
{"id":26,"email":"wredanp@biblegateway.com","password":"85Ql28L","role":"user",
  "uniqueStoreId":5},
{"id":27,"email":"tnodeq@jalbum.net","password":"DEpw7m","role":"admin",
  "uniqueStoreId":3},
{"id":28,"email":"dmattysr@1und1.de","password":"cXOdCB","role":"user",
  "uniqueStoreId":5},
{"id":29,"email":"tstrauns@amazon.co.jp","password":"vm2d9UHUC","role":"super-admin",
  "uniqueStoreId":7},
{"id":30,"email":"pclevelandt@seesaa.net","password":"AmPaV6ZSS","role":"user",
  "uniqueStoreId":3},
{"id":31,"email":"nmorebyu@buzzfeed.com","password":"z32ARkg1","role":"user",
  "uniqueStoreId":9},
{"id":32,"email":"mcheneyv@icq.com","password":"Axsw61","role":"admin",
  "uniqueStoreId":9},
{"id":33,"email":"fkilleleyw@home.pl","password":"f9zaiG","role":"admin",
  "uniqueStoreId":1},
{"id":34,"email":"mseifenmacherx@wp.com","password":"EQugdt7P","role":"user",
  "uniqueStoreId":1},
{"id":35,"email":"igaythwaitey@arizona.edu","password":"7LypXILcmks","role":"admin",
  "uniqueStoreId":7},
{"id":36,"email":"lpulhosterz@taobao.com","password":"8QRc71pv","role":"user",
  "uniqueStoreId":5},
{"id":37,"email":"bboribal10@tripadvisor.com","password":"O5ySj4DlN","role":"user",
  "uniqueStoreId":7},
{"id":38,"email":"kprickett11@army.mil","password":"0dT70fBkvT6","role":"user",
  "uniqueStoreId":8},
{"id":39,"email":"achasmar12@columbia.edu","password":"ZNcJinrbp","role":"user",
  "uniqueStoreId":9},
{"id":40,"email":"hknapper13@pen.io","password":"DY7XXh3","role":"user",
  "uniqueStoreId":7},
{"id":41,"email":"klazarus14@nyu.edu","password":"5Oa9PK8DRv","role":"admin",
  "uniqueStoreId":7},
{"id":42,"email":"eshimman15@google.ru","password":"Bt8DmMtjJPiX","role":"user",
  "uniqueStoreId":10},
{"id":43,"email":"klandreth16@xinhuanet.com","password":"bTVLrRT8","role":"admin",
  "uniqueStoreId":2},
{"id":44,"email":"mnoor17@utexas.edu","password":"o6SCV1wwd","role":"user",
  "uniqueStoreId":1},
{"id":45,"email":"bsulter18@princeton.edu","password":"61fvCWzSWU","role":"user",
  "uniqueStoreId":3},
{"id":46,"email":"bbrundale19@go.com","password":"2IABIDDCzZfH","role":"user",
  "uniqueStoreId":4},
{"id":47,"email":"arefford1a@1688.com","password":"bc7h7I","role":"user",
  "uniqueStoreId":5},
{"id":48,"email":"hhasser1b@uol.com.br","password":"9OOdzv4X","role":"user",
  "uniqueStoreId":1},
{"id":49,"email":"dharbard1c@opensource.org","password":"11q8p5gLV","role":"user",
  "uniqueStoreId":6},
{"id":50,"email":"kdorosario1d@dot.gov","password":"zhNC9gyF","role":"admin",
  "uniqueStoreId":5},
{"id":51,"email":"lcollacombe1e@studiopress.com","password":"Hml1fc2cX","role":"admin",
  "uniqueStoreId":10},
{"id":52,"email":"rwalsh1f@woothemes.com","password":"eHdOHH8VX4","role":"admin",
  "uniqueStoreId":9},
{"id":53,"email":"rdolan1g@berkeley.edu","password":"5vr1PJBo","role":"admin",
  "uniqueStoreId":10},
{"id":54,"email":"jsteer1h@feedburner.com","password":"mX45Zj99","role":"admin",
  "uniqueStoreId":8},
{"id":55,"email":"jknappe1i@army.mil","password":"JyPOdctMV","role":"user",
  "uniqueStoreId":5},
{"id":56,"email":"epolamontayne1j@epa.gov","password":"T2fI2bl1","role":"admin",
  "uniqueStoreId":5},
{"id":57,"email":"asimkin1k@taobao.com","password":"aNyF5oaGJ","role":"user",
  "uniqueStoreId":7},
{"id":58,"email":"mryal1l@hibu.com","password":"DFElLICoRr","role":"admin",
  "uniqueStoreId":4},
{"id":59,"email":"bvedstra1m@nhs.uk","password":"fnt1slPpE9r8","role":"user",
  "uniqueStoreId":6},
{"id":60,"email":"sgerin1n@wikispaces.com","password":"W7FHTm2JJXh","role":"user",
  "uniqueStoreId":5},
{"id":61,"email":"nfoggarty1o@ft.com","password":"3hk8uly48B02","role":"admin",
  "uniqueStoreId":4},
{"id":62,"email":"pbenardette1p@amazon.com","password":"kYjpwm","role":"user",
  "uniqueStoreId":1},
{"id":63,"email":"zroscam1q@youtube.com","password":"KiJUyH","role":"user",
  "uniqueStoreId":8},
{"id":64,"email":"lskitteral1r@virginia.edu","password":"pusSEaaaw4","role":"admin",
  "uniqueStoreId":6},
{"id":65,"email":"lweddeburnscrimgeour1s@usa.gov","password":"U9UCI6W","role":"user",
  "uniqueStoreId":7},
{"id":66,"email":"nasplin1t@admin.ch","password":"krY7gwF","role":"admin",
  "uniqueStoreId":10},
{"id":67,"email":"lvotier1u@archive.org","password":"tT2XYTRGv","role":"user",
  "uniqueStoreId":2},
{"id":68,"email":"crichard1v@bbb.org","password":"djqsQmxkO","role":"user",
  "uniqueStoreId":3},
{"id":69,"email":"ddanford1w@ameblo.jp","password":"5LxU1YJpGK6","role":"user",
  "uniqueStoreId":9},
{"id":70,"email":"thachard1x@dailymail.co.uk","password":"yvQarEIVF5S","role":"admin",
  "uniqueStoreId":1},
{"id":71,"email":"creck1y@archive.org","password":"fVgWMETW","role":"super-admin",
  "uniqueStoreId":3},
{"id":72,"email":"rlodge1z@unblog.fr","password":"x5io632","role":"user",
  "uniqueStoreId":5},
{"id":73,"email":"mmcnae20@indiatimes.com","password":"feRjOfCyKI","role":"admin",
  "uniqueStoreId":8},
{"id":74,"email":"mbrettle21@netvibes.com","password":"Xy8FHljHm","role":"user",
  "uniqueStoreId":3},
{"id":75,"email":"vbuller22@vimeo.com","password":"S7WUQgYL2JLu","role":"admin",
  "uniqueStoreId":5},
{"id":76,"email":"ebrecon23@irs.gov","password":"jsuMdK","role":"super-admin",
  "uniqueStoreId":7},
{"id":77,"email":"asokale24@bluehost.com","password":"kfJsGtdhU","role":"user",
  "uniqueStoreId":8},
{"id":78,"email":"dbuttrum25@constantcontact.com","password":"4JDMGHlXQ2","role":"user",
  "uniqueStoreId":5},
{"id":79,"email":"sloving26@tripod.com","password":"kLrciA0","role":"user",
  "uniqueStoreId":10},
{"id":80,"email":"phowsego27@goo.gl","password":"enG8usp","role":"super-admin",
  "uniqueStoreId":7},
{"id":81,"email":"ujosilevich28@google.com.br","password":"7SXaKuxSl","role":"user",
  "uniqueStoreId":4},
{"id":82,"email":"acramp29@1688.com","password":"Jhmpgd6touat","role":"user",
  "uniqueStoreId":5},
{"id":83,"email":"cbanfill2a@usa.gov","password":"SjcFOzWR","role":"user",
  "uniqueStoreId":9},
{"id":84,"email":"lendrizzi2b@tamu.edu","password":"4ywpYY","role":"user",
  "uniqueStoreId":4},
{"id":85,"email":"hnisen2c@networkadvertising.org","password":"W4x9kL","role":"user",
  "uniqueStoreId":2},
{"id":86,"email":"edonnan2d@tiny.cc","password":"n1uTpYT9Wv","role":"admin",
  "uniqueStoreId":7},
{"id":87,"email":"kbrinkman2e@spiegel.de","password":"Sjnx0Thy1hiw","role":"user",
  "uniqueStoreId":1},
{"id":88,"email":"edudman2f@shinystat.com","password":"taK1sDh7","role":"super-admin",
  "uniqueStoreId":9},
{"id":89,"email":"bdixcey2g@163.com","password":"2sUy6HeUCZt","role":"admin",
  "uniqueStoreId":1},
{"id":90,"email":"dsubhan2h@shop-pro.jp","password":"xaqQgPRBm","role":"user",
  "uniqueStoreId":8},
{"id":91,"email":"mpellew2i@marriott.com","password":"0PqMdFSMDT","role":"user",
  "uniqueStoreId":4},
{"id":92,"email":"jtuson2j@mashable.com","password":"kfj6Y31","role":"user",
  "uniqueStoreId":3},
{"id":93,"email":"jtamblyn2k@opera.com","password":"7o41t8EL","role":"user",
  "uniqueStoreId":8},
{"id":94,"email":"croskams2l@163.com","password":"iPxswpP","role":"user",
  "uniqueStoreId":5},
{"id":95,"email":"kvallentin2m@seattletimes.com","password":"MtzJ3XAxa","role":"user",
  "uniqueStoreId":4},
{"id":96,"email":"bchingedehals2n@delicious.com","password":"VSFxCG","role":"user",
  "uniqueStoreId":2},
{"id":97,"email":"lblackwood2o@sakura.ne.jp","password":"je3Z0T7rAY","role":"user",
  "uniqueStoreId":8},
{"id":98,"email":"ehodjetts2p@behance.net","password":"czJmJQ2NQknW","role":"user",
  "uniqueStoreId":5},
{"id":99,"email":"rkayzer2q@diigo.com","password":"lLynRur3","role":"user",
  "uniqueStoreId":6},
{"id":100,"email":"xchippendale2r@wired.com","password":"QlsbLyx8yBTD","role":"user",
  "uniqueStoreId":10}]

*/